#ifndef FLAMBROLA_H
#define FLAMBROLA_H 1

/*
 * This file is autogenerated from pl1 database
 * Do not edit manually!
 */
#define COMPRESSION_TYPE 1
#define PARAHASH_COUNT 1444
#define MBRPeriod 92
#define MBRFreq 16000
#define nb_diphone 38
#define max_frame 41
#define max_samples 3772
#endif

